name: Build and Publish
# Triggers the workflow on push or pull request events
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm i

      - name: Install Rocket.Chat Apps cli
        run: npm i -g @rocket.chat/apps-cli

      - name: ESLint check
        run: npm run lint

      - name: Typescript check
        run: npm run typecheck

      - name: Bundle App
        run: rc-apps package

      - name: Bundle App for Marketplace
        run: rc-apps package --no-compile

      - name: Set env with filename
        run: echo "COMPILED_APP_PACKAGE=$(echo ls dist/ | head -1)" >> $GITHUB_ENV

      - name: Extract compiled folder
        run: 7z x dist/$COMPILED_APP_PACKAGE -o$GITHUB_WORKSPACE/rawDist/ -y

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app.zip
          path: rawDist/
          if-no-files-found: error
          retention-days: 30
