name: Build and Publish
# Triggers the workflow on push or pull request events
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm i

      - name: Install Rocket.Chat Apps cli
        run: npm i -g @rocket.chat/apps-cli

      - name: ESLint check
        run: npm run lint

      - name: Typescript check
        run: npm run typecheck

      - name: Bundle App
        run: rc-apps package

      - name: Setup for uploading compiled app bundle
        run: echo "COMPILED_APP_PACKAGE=$(ls dist/ | head -1)" >> $GITHUB_ENV &&
          7z x dist/$COMPILED_APP_PACKAGE -o$GITHUB_WORKSPACE/compiledBundle/ -y &&
          echo "COMPILED_APP_PACKAGE_NAME=${COMPILED_APP_PACKAGE%.*}_compiled.zip" >> $GITHUB_ENV

      - name: Upload the compiled app bundle
        uses: actions/upload-artifact@v2.2.4
        with:
          name: compiled
          path: compiledBundle/
          if-no-files-found: error
          retention-days: 30
      
      - name: Cleanup compiled bundle
        run: rm -rf compiledBundle/ && rm -rf dist/

      - name: Setup for uploading non-compiled app bundle
        run: rc-apps package --no-compile && 
          echo "NON_COMPILED_APP_PACKAGE=$(ls dist/ | head -1)" >> $GITHUB_ENV &&
          7z x dist/$NON_COMPILED_APP_PACKAGE -o$GITHUB_WORKSPACE/nonCompiledBundle/ -y &&
          echo "NON_COMPILED_APP_PACKAGE_NAME=${NON_COMPILED_APP_PACKAGE%.*}_non_compiled.zip" >> $GITHUB_ENV

      - name: Upload the non-compiled app bundle
        uses: actions/upload-artifact@v2.2.4
        with:
          name: non_compiled
          path: nonCompiledBundle/
          if-no-files-found: error
          retention-days: 30
