---
name: "pre-release"

on:
  push:
    branches:
      - "deploy"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm i

      - name: Install Rocket.Chat Apps cli
        run: npm i -g @rocket.chat/apps-cli

      - name: ESLint check
        run: npm run lint

      - name: Typescript check
        run: npm run typecheck

      - name: Bundle App
        run: rc-apps package 

      - name: Create compiled package bundle
        run: pwd && echo "COMPILED_APP_PACKAGE=$(ls dist/ | head -1)" >> $GITHUB_ENV &&
          echo "COMPILED_APP_PACKAGE_NAME=${COMPILED_APP_PACKAGE%.*}_compiled.zip" >> $GITHUB_ENV &&
          echo "COMPILED_APP_PACKAGE - ${COMPILED_APP_PACKAGE}" &&
          echo "COMPILED_APP_PACKAGE_NAME - ${COMPILED_APP_PACKAGE_NAME}" &&
          mkdir -p finalPackageForRelease/ &&
          mv dist/$COMPILED_APP_PACKAGE finalPackageForRelease/$COMPILED_APP_PACKAGE_NAME &&
          rm -rf dist/ &&
          ls finalPackageForRelease/

      - name: create non-compiled package bundle
        run: rc-apps package --no-compile && 
          echo "NON_COMPILED_APP_PACKAGE=$(ls dist/ | head -1)" >> $GITHUB_ENV && echo "${NON_COMPILED_APP_PACKAGE}" &&
          echo "NON_COMPILED_APP_PACKAGE_NAME=${NON_COMPILED_APP_PACKAGE%.*}_non_compiled.zip" >> $GITHUB_ENV && echo "${NON_COMPILED_APP_PACKAGE_NAME}" &&
          mv dist/$NON_COMPILED_APP_PACKAGE finalPackageForRelease/$NON_COMPILED_APP_PACKAGE_NAME

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            - finalPackageForRelease/$COMPILED_APP_PACKAGE_NAME
            - finalPackageForRelease/$NON_COMPILED_APP_PACKAGE_NAME