---
name: "pre-release"

on:
  push:
    branches:
      - "deploy"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm i

      - name: Install Rocket.Chat Apps cli
        run: npm i -g @rocket.chat/apps-cli

      - name: ESLint check
        run: npm run lint

      - name: Typescript check
        run: npm run typecheck

      - name: Create compiled package bundle
        run: |
          chmod +x ./.scripts/compiledPackage.sh
          ./.scripts/compiledPackage.sh

      - name: Create non-compiled package bundle
        run: |
          chmod +x ./.scripts/nonCompiledPackage.sh
          ./.scripts/nonCompiledPackage.sh

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            - $GITHUB_WORKSPACE/finalPackageForRelease/dialogflow_1.2.4_compiled.zip
            - $GITHUB_WORKSPACE/finalPackageForRelease/dialogflow_1.2.4_non_compiled.zip